version: "1.0"

services:
    food-totem-database:
        image: mysql:8.0.33
        environment:
            MYSQL_ROOT_PASSWORD: StRoNg_PaSsWoRd
            MYSQL_DATABASE: foodtotem
            MYSQL_USER: user
            MYSQL_PASSWORD: uSeRpAsSwOrD
        ports:
            - "33060:3306"
        container_name: food-totem-database
        networks:
            - foodtotem-network
    food-totem-mq:
        image: rabbitmq:management
        ports:
            - "5672:5672"
            - "15672:15672"
        container_name: food-totem-mq
        networks:
            - foodtotem-network
    food-totem-api:
        build:
            context: ../../src
            dockerfile: Dockerfile
        ports:
            - "3000:80"
        container_name: food-totem-api
        depends_on:
            - food-totem-database
            - food-totem-mq
        environment:
            RabbitMQ__HostName: food-totem-mq
            RabbitMQ__Port: 5672
            RabbitMQ__Username: guest
            RabbitMQ__Password: guest
            ConnectionStrings__DefaultConnection: Server=food-totem-database;Port=3306;Database=foodtotem;Uid=user;Pwd=uSeRpAsSwOrD;
            DemandServiceUrl: http://food-totem-demand:80
            PaymentServiceUrl: http://food-totem-payment:80
            CatalogServiceUrl: http://food-totem-catalog:80
            JWTIssuerSigningKey: <YourSecretKey>
            AuthenticationUrl: <YourLambdaUrl>
        networks:
            - foodtotem-network
networks:
    foodtotem-network:
        driver: bridge
