apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      name: database
      labels:
        app: database
    spec:
      containers:
      - name: database
        image: mysql:8.0.33
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: food-totem-db-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app: database
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: database
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: food-totem-db-configmap
data:
  MYSQL_ROOT_PASSWORD: StRoNg_PaSsWoRd
  MYSQL_DATABASE: foodtotem
  MYSQL_USER: user
  MYSQL_PASSWORD: uSeRpAsSwOrD
