version: "1.0"

services:
    mysql-database:
        image: mysql:8.0.33
        environment:
            MYSQL_DATABASE: foodtotem
            MYSQL_ROOT_PASSWORD: StRoNg_PaSsWoRd
            MYSQL_USER: user
            MYSQL_PASSWORD: uSeRpAsSwOrD
        ports:
            - "3306:3306"
        container_name: database
        networks:
            - foodtotem-network
    # api:
    #     # image: leonardoavila98/food-totem-api:2.0.0
    #     build:
    #         context: .
    #         dockerfile: Dockerfile
    #     ports:
    #         - "8080:80"
    #     depends_on:
    #         - mysql-database
    #     networks:
    #         - foodtotem-network
    #     restart: always
networks:
    foodtotem-network:
        driver: bridge

    
    