version: "1.0"

services:
    database:
        image: mysql:8.0.33
        environment:
            MYSQL_ROOT_PASSWORD: StRoNg_PaSsWoRd
            MYSQL_DATABASE: foodtotem
            MYSQL_USER: user
            MYSQL_PASSWORD: uSeRpAsSwOrD
        ports:
            - "3306:3306"
        container_name: database
        networks:
            - foodtotem-network
    api:
        image: food-totem-api
        build:
            context: .
            dockerfile: Adapters/Driver/FoodTotem.API/Dockerfile
        ports:
            - "8080:80"
        depends_on:
            - database
        networks:
            - foodtotem-network
        restart: always
networks:
    foodtotem-network:
        driver: bridge

    
    