# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build and Publish

on:
  push:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update AppSettings
      uses: microsoft/variable-substitution@v1
      with:
        files: src/Adapters/Driver/FoodTotem.API/appsettings.json
      env:
        ConnectionStrings.DefaultConnection: ${{ secrets.MYSQL_RDS_CONNECTION_STRING }}
        AccessToken: ${{ secrets.MERCADO_PAGO_ACCESS_TOKEN }}
        ExternalPosId: ${{ secrets.MERCADO_PAGO_EXTERNAL_POS_ID }}
        UserId: ${{ secrets.MERCADO_PAGO_USER_ID }}
        BaseUrl: ${{ secrets.MERCADO_PAGO_API_URL }}
        JWTIssuerSigningKey: ${{ secrets.JWT_ISSUER_SIGNING_KEY }}
        AuthenticationUrl: ${{ secrets.AUTHENTICATION_URL }}
 
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src --no-restore
    - name: Test
      run: dotnet test src --no-build --verbosity normal
    
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Docker Setup QEMU
      if: github.ref == 'refs/heads/main'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: amd64,arm64
    - name: Set-up Docker Buildx
      if: github.ref == 'refs/heads/main'
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v3
      with:
        context: src
        file: src/Dockerfile
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/food-totem-api:latest
      
