name: deploy

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Update AppSettings
      uses: microsoft/variable-substitution@v1
      with:
        files: src/Adapters/Driver/FoodTotem.API/appsettings.json
      env:
        JWTIssuerSigningKey: ${{ secrets.JWT_ISSUER_SIGNING_KEY }}
 
    - name: Login to Docker Hub
      if: github.ref == 'refs/heads/main'
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
    - name: Docker Setup QEMU
      if: github.ref == 'refs/heads/main'
      uses: docker/setup-qemu-action@v3
      with:
        platforms: amd64,arm64
    - name: Set-up Docker Buildx
      if: github.ref == 'refs/heads/main'
      uses: docker/setup-buildx-action@v3
    - name: Build and push
      if: github.ref == 'refs/heads/main'
      uses: docker/build-push-action@v3
      with:
        context: src
        file: src/Dockerfile
        platforms: linux/amd64,linux/arm64/v8
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/food-totem-api:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.LAB_ACCOUNT_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7
  
    - name: Terraform Init
      run: terraform init
      working-directory: ./infra/terraform

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
      working-directory: ./infra/terraform
      env:
        TF_VAR_lab_account_id: ${{ secrets.LAB_ACCOUNT_ID }}
        TF_VAR_lab_account_region: ${{ secrets.LAB_ACCOUNT_REGION }}
        TF_VAR_food_totem_api_image: ${{ secrets.API_IMAGE }}
        TF_VAR_mysql_password: ${{ secrets.MYSQL_PASSWORD }}
        TF_VAR_mysql_user: ${{ secrets.MYSQL_USER }}